"""KHOA ODMI OpenAPI 서비스를 위한 Python 헬퍼."""

from .client import KhoaClient, KhoaODMIClient
from .exceptions import (
    KhoaAuthError,
    KhoaError,
    KhoaNoDataError,
    KhoaParseError,
    KhoaRateLimitError,
    KhoaRequestError,
    KhoaServerError,
)
from .models import (
    BeachIndexForecast,
    BeachIndexPlace,
    BeachSearchObservation,
    BeachSearchResult,
    MarineIndexForecast,
    MarineIndexPlace,
    Observatory,
    Page,
    RawRecord,
    ResponseContext,
    RomsPrediction,
)
from .observatories import (
    BEACH_INFO_MODIFY_CYCLE,
    BEACH_INFO_TITLE,
    BEACH_INFO_UPDATE_INTERVAL_MINUTES,
    BEACH_OBSERVATORIES,
    BEACH_OBSERVATORY_COUNT,
    BEACH_OBSERVATORY_SOURCE_DATE,
    BEACH_OBSERVATORY_SOURCE_SHA256,
    BEACH_OPENAPI_ID,
    DEFAULT_ADDRESS_SEARCH_OFFSETS_DEGREES,
    KHOA_OPENAPI_DETAIL_URL,
    KHOA_OPENAPI_INFO_URL,
    enrich_observatory_addresses,
    fetch_beach_observatories,
    fetch_observatory_list,
    fetch_openapi_info,
    get_beach_observatories,
    get_builtin_observatory_list,
)
from .services import (
    DEFAULT_BASE_URL,
    KHOA_ODMI_LIST_URL,
    SERVICE_BY_KEY,
    SERVICE_DEFINITIONS,
    ServiceDefinition,
    get_service,
)

__all__ = [
    "DEFAULT_BASE_URL",
    "BEACH_INFO_MODIFY_CYCLE",
    "BEACH_INFO_TITLE",
    "BEACH_INFO_UPDATE_INTERVAL_MINUTES",
    "BEACH_OBSERVATORIES",
    "BEACH_OBSERVATORY_COUNT",
    "BEACH_OBSERVATORY_SOURCE_DATE",
    "BEACH_OBSERVATORY_SOURCE_SHA256",
    "BEACH_OPENAPI_ID",
    "DEFAULT_ADDRESS_SEARCH_OFFSETS_DEGREES",
    "KHOA_ODMI_LIST_URL",
    "KHOA_OPENAPI_DETAIL_URL",
    "KHOA_OPENAPI_INFO_URL",
    "SERVICE_BY_KEY",
    "SERVICE_DEFINITIONS",
    "BeachIndexForecast",
    "BeachIndexPlace",
    "BeachSearchObservation",
    "BeachSearchResult",
    "KhoaAuthError",
    "KhoaClient",
    "KhoaError",
    "KhoaNoDataError",
    "KhoaODMIClient",
    "KhoaParseError",
    "KhoaRateLimitError",
    "KhoaRequestError",
    "KhoaServerError",
    "MarineIndexForecast",
    "MarineIndexPlace",
    "Observatory",
    "Page",
    "RawRecord",
    "ResponseContext",
    "RomsPrediction",
    "ServiceDefinition",
    "enrich_observatory_addresses",
    "fetch_beach_observatories",
    "fetch_observatory_list",
    "fetch_openapi_info",
    "get_beach_observatories",
    "get_builtin_observatory_list",
    "get_service",
]
